#!/bin/sh

#PBS -l nodes=1:ppn=32,walltime=01:00:00
#PBS -N HPC3_Part3_Node1
#PBS -M gmani001@ucr.edu
#PBS -m abe

module load gcc-4.6.2
module load mvapich2-1.9a2/gnu-4.6.2

PBS_O_WORKDIR=/home/$USER/HPC3

cd $PBS_O_WORKDIR

echo >> RESULTS.txt
echo "PART3" >> RESULTS.txt
echo >> RESULTS.txt

mpirun ./HPC3_p3 10000000000 1 >> RESULTS.txt
