#!/bin/sh

#PBS -l nodes=8:ppn=32,walltime=00:05:00
#PBS -N HPC3
#PBS -M gmani001@ucr.edu
#PBS -m abe

module load gcc-4.6.2
module load mvapich2-1.9a2/gnu-4.6.2

PBS_O_WORKDIR=/home/gmani001/HPC3

cd $PBS_O_WORKDIR

mpirun ./Seiving_Prime 10000000000 8 >> Prime.txt
